src/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Company.WebApplication1.Data;

namespace Company.WebApplication1.Controllers
{
    [Route("[controller]/[action]")]
    public class AccountController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger _logger;

        public AccountController(SignInManager<ApplicationUser> signInManager, ILogger<AccountController> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            return RedirectToPage("/Index");
        }
    }
}

src/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Company.WebApplication1.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Company.WebApplication1.Controllers
{
    public class ProfileController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<ProfileController> _logger;

        public ProfileController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ILogger<ProfileController> logger)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

        private ApplicationUser _currentUser;

        public ApplicationUser CurrentUser
        {
            get
            {
                if (_currentUser == null)
                {
                    var user = _userManager.GetUserAsync(User);
                    if (user == null)
                    {
                        throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
                    }

                    _currentUser = user.Result;
                }
                return _currentUser;
            }
        }

        public bool IsEmailConfirmed
        {
            get
            {
                return _userManager.IsEmailConfirmedAsync(CurrentUser).Result;
            }
        }

        public bool IsHasPassword
        {
            get
            {
                return _userManager.HasPasswordAsync(CurrentUser).Result;
            }
        }

        public class ChangePasswordInput
        {
            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "Current password")]
            public string OldPassword { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "New password")]
            public string NewPassword { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm new password")]
            [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(ChangePasswordInput model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var changePasswordResult = await _userManager.ChangePasswordAsync(CurrentUser, model.OldPassword, model.NewPassword);
            if (!changePasswordResult.Succeeded)
            {
                foreach (var error in changePasswordResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return BadRequest(ModelState);
            }

            await _signInManager.SignInAsync(CurrentUser, isPersistent: false);
            _logger.LogInformation("User changed their password successfully.");

            return Ok("Your password has been changed.");
        }

        public class SetPasswordInput
        {
            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "New password")]
            public string NewPassword { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm new password")]
            [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetPassword(SetPasswordInput model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var addPasswordResult = await _userManager.AddPasswordAsync(CurrentUser, model.NewPassword);
            if (!addPasswordResult.Succeeded)
            {
                foreach (var error in addPasswordResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return BadRequest(ModelState);
            }

            await _signInManager.SignInAsync(CurrentUser, isPersistent: false);
            _logger.LogInformation("User set password successfully.");

            return Ok("Your password has been set.");
        }
    }
}

src/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Company.WebApplication1.Controllers
{
    public class SettingsController : Controller
    {
        public IActionResult Index()
        {
            return RedirectToPage("/Settings/Profile");
        }

        public IActionResult TwoFactorAuth()
        {
            return RedirectToPage("/Settings/TwoFactorAuth/Config");
        }
    }
}

src/Pages/Account/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Account
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/Pages/Account/ConfirmEmail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Company.WebApplication1.Data;

namespace Company.WebApplication1.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public ConfirmEmailModel(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{userId}'.");
            }

            var result = await _userManager.ConfirmEmailAsync(user, code);
            if (!result.Succeeded)
            {
                throw new ApplicationException($"Error confirming email for user with ID '{userId}':");
            }

            return Page();
        }
    }
}

src/Pages/Account/ForgotPassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Company.WebApplication1.Data;
using Company.WebApplication1.Services;
using Company.WebApplication1.Services.Mail;

namespace Company.WebApplication1.Pages.Account
{
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMailManager _emailSender;

        public ForgotPasswordModel(UserManager<ApplicationUser> userManager, IMailManager emailSender)
        {
            _userManager = userManager;
            _emailSender = emailSender;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(Input.Email);
                if (user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return RedirectToPage("./ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please 
                // visit https://go.microsoft.com/fwlink/?LinkID=532713
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                var callbackUrl = Url.ResetPasswordCallbackLink(user.Id, code, Request.Scheme);
                await _emailSender.SendResetPasswordAsync(Input.Email, callbackUrl);
                return RedirectToPage("./ForgotPasswordConfirmation");
            }

            return Page();
        }
    }
}

src/Pages/Account/ForgotPasswordConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Account
{
    public class ForgotPasswordConfirmationModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/Pages/Account/Lockout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Account
{
    public class LockoutModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/Pages/Account/ResetPasswordConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Account
{
    public class ResetPasswordConfirmationModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/Pages/Account/SignedOut.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Account
{
    public class SignedOutModel : PageModel
    {
        public IActionResult OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                // Redirect to home page if the user is authenticated.
                return RedirectToPage("/Index");
            }

            return Page();
        }
    }
}

src/Pages/Examples/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Examples
{
    public class ProfileModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/Pages/Settings/Account.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Company.WebApplication1.Data;
using Company.WebApplication1.Services.Mail;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Settings
{
    public class AccountModel : PageModel
    {
        public AccountModel() 
        {
        }

        public IActionResult OnGet()
        {
            return Page();
        }
    }
}

src/Pages/Settings/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Company.WebApplication1.Data;
using Company.WebApplication1.Services.Mail;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Settings
{
    public class ProfileModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IMailManager _emailSender;

        public ProfileModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, IMailManager emailSender) 
            //: base(userManager, signInManager, emailSender)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
        }

        [BindProperty]
        [Required]
        public string UserName { get; set; }

        [BindProperty]
        [Required][EmailAddress]
        public string Email { get; set; }

        [BindProperty]
        [Phone][Display(Name = "Phone number")]
        public string PhoneNumber { get; set; }

        public bool IsEmailConfirmed { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null)
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            UserName = user.UserName;
            Email = user.Email;
            PhoneNumber = user.PhoneNumber;

            IsEmailConfirmed = await _userManager.IsEmailConfirmedAsync(user);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null) throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            if (UserName != user.UserName)
            {
                var setUserNameResult = await _userManager.SetUserNameAsync(user, UserName);
                if (!setUserNameResult.Succeeded)
                {
                    TempData["StatusMessage"] = $"Error on changing username." + string.Join(". ", setUserNameResult.Errors.Select(p => p.Description));
                    return RedirectToPage();
                    //throw new ApplicationException($"Unexpected error occurred setting email for user with ID '{user.Id}'.");
                }
            }

            if (Email != user.Email)
            {
                var setEmailResult = await _userManager.SetEmailAsync(user, Email);
                if (!setEmailResult.Succeeded)
                {
                    TempData["StatusMessage"] = $"Error on changing email. '{Email}' use in other account and must be unique.";
                    return RedirectToPage();
                    //throw new ApplicationException($"Unexpected error occurred setting email for user with ID '{user.Id}'.");
                }
            }

            if (PhoneNumber != user.PhoneNumber)
            {
                var setPhoneResult = await _userManager.SetPhoneNumberAsync(user, PhoneNumber);
                if (!setPhoneResult.Succeeded)
                {
                    throw new ApplicationException($"Unexpected error occurred setting phone number for user with ID '{user.Id}'.");
                }
            }

            TempData["StatusMessage"] = "Your profile has been updated";

            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostSendVerificationEmailAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            ApplicationUser user = await _userManager.GetUserAsync(User);
            if (user == null) throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");

            var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
            var callbackUrl = Url.EmailConfirmationLink(user.Id, code, Request.Scheme);
            await _emailSender.SendEmailConfirmationAsync(user.Email, callbackUrl);

            TempData["StatusMessage"] = "Verification email sent. Please check your email.";

            return RedirectToPage();
        }
    }
}

src/Pages/Settings/Account.cshtml
@page
@model AccountModel
@{
    ViewData["Title"] = "Account";
}

@inject Company.WebApplication1.Services.Profile.ProfileManager ProfileManager
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        My Account
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Settings</a></li>
        <li class="active">My Account</li>
    </ol>
</section>


<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-lg-2">

        </div>
        <!-- /.col -->

        <div class="col-lg-8">
            <!-- Account Settings -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Public profile</h3>
                </div>
                <div class="box-body box-account">
                    <form id="formChangePassword" asp-controller="Profile" asp-action="@(ProfileManager.IsHasPassword(ProfileManager.CurrentUser) ? "ChangePassword" : "SetPassword")"
                          class="form-horizontal" method="post">
                        @if (ProfileManager.IsHasPassword(ProfileManager.CurrentUser))
                        {
                            <div class="form-group">

                                <label for="OldPassword" class="col-sm-2 control-label">Current Password</label>

                                <div class="col-sm-10">
                                    <input type="password" class="form-control" name="OldPassword" placeholder="Current password"
                                           data-val="true"
                                           data-val-required="The Current Password is required.">
                                    <span class="field-validation-valid help-block"
                                          data-valmsg-for="OldPassword" data-valmsg-replace="true"></span>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="alert alert-info alert-dismissible" role="alert">
                                You do not have a local username/password for this site. Add a local
                                account so you can log in without an external login.
                            </div>
                        }
                        <div class="form-group">
                            <label for="inputNewPassword" class="col-sm-2 control-label">New Password</label>

                            <div class="col-sm-10">
                                <input type="password" class="form-control" id="inputNewPassword" name="NewPassword" placeholder="New password"
                                       data-val="true"
                                       data-val-length="The Password must be at least 6 and at max 100 characters long."
                                       data-val-length-max="100"
                                       data-val-length-min="6"
                                       data-val-regex="The field Password must match the regular expression &#x27;^((?=.*[a-z])(?=.*[A-Z])(?=.*\d).&#x2B;$)&#x27;."
                                       data-val-regex-pattern="^((?=.*[a-z])(?=.*[A-Z])(?=.*\d).&#x2B;$)"
                                       data-val-required="The Password field is required.">
                                <span class="field-validation-valid help-block"
                                      data-valmsg-for="NewPassword"
                                      data-valmsg-replace="true"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputConfirmPassword" class="col-sm-2 control-label">Confirm Password</label>

                            <div class="col-sm-10">
                                <input type="password" class="form-control" id="inputConfirmPassword" name="ConfirmPassword" placeholder="Confirm password"
                                       data-val="true"
                                       data-val-equalto="The password and confirmation password do not match."
                                       data-val-equalto-other="NewPassword">
                                <span class="field-validation-valid help-block"
                                      data-valmsg-for="ConfirmPassword"
                                      data-valmsg-replace="true"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                @Html.AntiForgeryToken()
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                        <div id="panelChangePasswordErrors" class="alert alert-danger" style="display:none;"></div>
                    </form>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->

        <div class="col-lg-2">

        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->

</section>
<!-- /.content -->

@section Scripts {
    <!-- Page script -->
    <script>
        $(function () {
            $("#formChangePassword").submit(function (e) {
                e.preventDefault();

                if (!$("#formChangePassword").valid())
                    return;

                var form = $(this);
                var data = form.serialize();

                $('#panelChangePasswordErrors').hide();
                $('#panelChangePasswordErrors').empty();

                $.ajax({
                    url: form.attr("action"), // "/Profile/ChangePassword",
                    contentType: "application/x-www-form-urlencoded; charset=utf-8",
                    method: "POST",
                    data: data,
                    success: function (user) {
                        alert("Password Changed!");
                        form[0].reset();
                    },
                    error: function (jxqr, error, status) {
                        // парсинг json-объекта
                        console.log(jxqr);
                        console.log(error);
                        console.log(status);
                        if (jxqr.responseText === "") {
                            $('#panelChangePasswordErrors').append("<p>" + jxqr.statusText + "</p>");
                        }
                        else {
                            var response = JSON.parse(jxqr.responseText);
                            // добавляем общие ошибки модели
                            if (response) {

                                $.each(response, function (index, item) {
                                    $('#panelChangePasswordErrors').append("<p>" + item + "</p>");
                                });
                            }
                            // добавляем ошибки свойства Name
                            if (response['Name']) {

                                $.each(response['Name'], function (index, item) {
                                    $('#panelChangePasswordErrors').append("<p>" + item + "</p>");
                                });
                            }
                            // добавляем ошибки свойства Age
                            if (response['Age']) {
                                $.each(response['Age'], function (index, item) {
                                    $('#panelChangePasswordErrors').append("<p>" + item + "</p>");
                                });
                            }
                        }

                        $('#panelChangePasswordErrors').show();
                    }
                })
            });
        })
    </script>
}

src/Pages/Settings/Profile.cshtml
@page
@model ProfileModel
@{
    ViewData["Title"] = "Profile";
}

@inject Company.WebApplication1.Services.Profile.ProfileManager ProfileManager

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        My Profile
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Settings</a></li>
        <li class="active">My Profile</li>
    </ol>
</section>


<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-lg-2">

        </div>
        <!-- /.col -->

        <div class="col-lg-8">

            <!-- Profile Settings -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Public profile</h3>
                </div>
                <div class="box-body box-profile">
                    <form class="form-horizontal" method="post">
                        <div class="form-group">
                            <label for="inputUserName" class="col-sm-2 control-label">Username</label>

                            <div class="col-sm-10">
                                <input asp-for="UserName" class="form-control" id="inputUserName" placeholder="Username">
                                <span asp-validation-for="UserName" class="help-block"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                            <div class="col-sm-10">
                                @if (ProfileManager.IsEmailConfirmed(ProfileManager.CurrentUser))
                                {
                                    <div class="input-group">
                                        <input asp-for="Email" type="email" class="form-control" id="inputEmail" placeholder="Email">
                                        <span class="input-group-addon" aria-hidden="true"><span class="glyphicon glyphicon-ok text-success"></span></span>
                                    </div>
                                }
                                else
                                {
                                    <input asp-for="Email" type="email" class="form-control" id="inputEmail" placeholder="Email">
                                    <button asp-page-handler="SendVerificationEmail" class="btn btn-link">Send verification email</button>
                                }
                                <span asp-validation-for="Email" class="help-block"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPhone" class="col-sm-2 control-label">Phone</label>

                            <div class="col-sm-10">
                                <input asp-for="PhoneNumber" class="form-control" id="inputPhoneNumber" placeholder="Phone" data-inputmask='"mask": "+7 (999) 999-9999"' data-mask>
                                <span asp-validation-for="PhoneNumber" class="help-block"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->

        <div class="col-lg-2">

        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->

</section>
<!-- /.content -->

@section Scripts {
    <!-- InputMask -->
    <script src="~/plugins/input-mask/jquery.inputmask.js"></script>
    <script src="~/plugins/input-mask/jquery.inputmask.date.extensions.js"></script>
    <script src="~/plugins/input-mask/jquery.inputmask.extensions.js"></script>

    <!-- Page script -->
    <script>
        $(function () {
            //InputMask
            $('[data-mask]').inputmask();
        });
    </script>
}