src/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Company.WebApplication1.Data;

namespace Company.WebApplication1.Controllers
{
    [Route("[controller]/[action]")]
    public class AccountController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger _logger;

        public AccountController(SignInManager<ApplicationUser> signInManager, ILogger<AccountController> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            return RedirectToPage("/Index");
        }
    }
}

src/Pages/Account/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Account
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/Pages/Account/ConfirmEmail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Company.WebApplication1.Data;

namespace Company.WebApplication1.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public ConfirmEmailModel(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGetAsync(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{userId}'.");
            }

            var result = await _userManager.ConfirmEmailAsync(user, code);
            if (!result.Succeeded)
            {
                throw new ApplicationException($"Error confirming email for user with ID '{userId}':");
            }

            return Page();
        }
    }
}

src/Pages/Account/ExternalLogin.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Company.WebApplication1.Data;

namespace Company.WebApplication1.Pages.Account
{
    public class ExternalLoginModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<ExternalLoginModel> _logger;

        public ExternalLoginModel(
            SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager,
            ILogger<ExternalLoginModel> logger)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string LoginProvider { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public IActionResult OnGetAsync()
        {
            return RedirectToPage("./Login");
        }

        public IActionResult OnPost(string provider, string returnUrl = null)
        {
            // Request a redirect to the external login provider.
            var redirectUrl = Url.Page("./ExternalLogin", pageHandler: "Callback", values: new { returnUrl });
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return new ChallengeResult(provider, properties);
        }

        public async Task<IActionResult> OnGetCallbackAsync(string returnUrl = null, string remoteError = null)
        {
            if (remoteError != null)
            {
                ErrorMessage = $"Error from external provider: {remoteError}";
                return RedirectToPage("./Login");
            }
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                return RedirectToPage("./Login");
            }

            // Sign in the user with this external login provider if the user already has a login.
            var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor : true);
            if (result.Succeeded)
            {
                _logger.LogInformation("{Name} logged in with {LoginProvider} provider.", info.Principal.Identity.Name, info.LoginProvider);
                return LocalRedirect(Url.GetLocalUrl(returnUrl));
            }
            if (result.IsLockedOut)
            {
                return RedirectToPage("./Lockout");
            }
            else
            {
                // If the user does not have an account, then ask the user to create an account.
                ReturnUrl = returnUrl;
                LoginProvider = info.LoginProvider;
                if (info.Principal.HasClaim(c => c.Type == ClaimTypes.Email))
                {
                    Input = new InputModel
                    {
                        Email = info.Principal.FindFirstValue(ClaimTypes.Email)
                    };
                }
                return Page();
            }
        }

        public async Task<IActionResult> OnPostConfirmationAsync(string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                // Get the information about the user from the external login provider
                var info = await _signInManager.GetExternalLoginInfoAsync();
                if (info == null)
                {
                    throw new ApplicationException("Error loading external login information during confirmation.");
                }
                var user = new ApplicationUser { UserName = Input.Email, Email = Input.Email, EmailConfirmed = true };
                var result = await _userManager.CreateAsync(user);
                if (result.Succeeded)
                {
                    result = await _userManager.AddLoginAsync(user, info);
                    if (result.Succeeded)
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        _logger.LogInformation("User created an account using {Name} provider.", info.LoginProvider);
                        return LocalRedirect(Url.GetLocalUrl(returnUrl));
                    }
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            ReturnUrl = returnUrl;
            return Page();
        }
    }
}

src/Pages/Account/ForgotPassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Company.WebApplication1.Data;
using Company.WebApplication1.Services;
using Company.WebApplication1.Services.Mail;

namespace Company.WebApplication1.Pages.Account
{
    public class ForgotPasswordModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMailManager _emailSender;

        public ForgotPasswordModel(UserManager<ApplicationUser> userManager, IMailManager emailSender)
        {
            _userManager = userManager;
            _emailSender = emailSender;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(Input.Email);
                if (user == null || !(await _userManager.IsEmailConfirmedAsync(user)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return RedirectToPage("./ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please 
                // visit https://go.microsoft.com/fwlink/?LinkID=532713
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                var callbackUrl = Url.ResetPasswordCallbackLink(user.Id, code, Request.Scheme);
                await _emailSender.SendResetPasswordAsync(Input.Email, callbackUrl);
                return RedirectToPage("./ForgotPasswordConfirmation");
            }

            return Page();
        }
    }
}

src/Pages/Account/ForgotPasswordConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Account
{
    public class ForgotPasswordConfirmationModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/Pages/Account/Lockout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Company.WebApplication1.Pages.Account
{
    public class LockoutModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

src/Pages/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Company.WebApplication1.Data;

namespace Company.WebApplication1.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<ApplicationUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public string ReturnUrl { get; set; }

        [TempData]
        public string ErrorMessage { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            ReturnUrl = returnUrl;

            if (ModelState.IsValid)
            {
                var user = await _signInManager.UserManager.FindByEmailAsync(Input.Email);
                
                if (user != null) {
                    // This doesn't count login failures towards account lockout
                    // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                    var result = await _signInManager.PasswordSignInAsync(user, Input.Password, Input.RememberMe, lockoutOnFailure: true);
                    if (result.Succeeded)
                    {
                        _logger.LogInformation("User logged in.");
                        return LocalRedirect(Url.GetLocalUrl(returnUrl));
                    }
                    if (result.RequiresTwoFactor)
                    {
                        return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                    }
                    if (result.IsLockedOut)
                    {
                        _logger.LogWarning("User account locked out.");
                        return RedirectToPage("./Lockout");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Email or password is incorrect.");
                        return Page();
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "User with this email not found");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

src/Pages/Account/LoginWith2fa.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Company.WebApplication1.Data;

namespace Company.WebApplication1.Pages.Account
{
    public class LoginWith2faModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<LoginWith2faModel> _logger;

        public LoginWith2faModel(SignInManager<ApplicationUser> signInManager, ILogger<LoginWith2faModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public bool RememberMe { get; set; }

        public string ReturnUrl { get; set; }

        public class InputModel
        {
            [Required]
            [StringLength(7, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Text)]
            [Display(Name = "Authenticator code")]
            public string TwoFactorCode { get; set; }

            [Display(Name = "Remember this machine")]
            public bool RememberMachine { get; set; }
        }

        public async Task<IActionResult> OnGetAsync(bool rememberMe, string returnUrl = null)
        {
            // Ensure the user has gone through the username & password screen first
            var user = await _signInManager.GetTwoFactorAuthenticationUserAsync();

            if (user == null)
            {
                return RedirectToPage("./Login");
            }

            ReturnUrl = returnUrl;
            RememberMe = rememberMe;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(bool rememberMe, string returnUrl = null)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _signInManager.GetTwoFactorAuthenticationUserAsync();
            if (user == null)
            {
                throw new ApplicationException($"Unable to load two-factor authentication user.");
            }

            var authenticatorCode = Input.TwoFactorCode.Replace(" ", string.Empty).Replace("-", string.Empty);

            var result = await _signInManager.TwoFactorAuthenticatorSignInAsync(authenticatorCode, rememberMe, Input.RememberMachine);

            if (result.Succeeded)
            {
                _logger.LogInformation("User with ID '{UserId}' logged in with 2fa.", user.Id);
                return LocalRedirect(Url.GetLocalUrl(returnUrl));
            }
            else if (result.IsLockedOut)
            {
                _logger.LogWarning("User with ID '{UserId}' account locked out.", user.Id);
                return RedirectToPage("./Lockout");
            }
            else
            {
                _logger.LogWarning("Invalid authenticator code entered for user with ID '{UserId}'.", user.Id);
                ModelState.AddModelError(string.Empty, "Invalid authenticator code.");
                return Page();
            }
        }  
    }
}

src/Pages/Account/AccessDenied.cshtml
@page
@model AccessDeniedModel
@{
    ViewData["Title"] = "Access denied";
}

<div class="login-box-body">
    <p class="login-box-msg">
        You do not have access to this resource. <br />
        Please <a asp-page="./Login">click here to log in</a>.
    </p>
</div>
<!-- /.login-box-body -->

src/Pages/Account/ConfirmEmail.cshtml
@page
@model ConfirmEmailModel
@{
    ViewData["Title"] = "Confirm email";
}
<div class="login-box-body">
    <p class="login-box-msg">
        Thank you for confirm your email. <br />
        Please <a asp-page="./Login">click here to log in</a>.
    </p>
</div>
<!-- /.login-box-body -->

src/Pages/Account/ExternalLogin.cshtml
@page
@model ExternalLoginModel
@{
    ViewData["Title"] = "Register";
}

<div class="login-box-body">
    <p class="login-box-msg">Associate your @Model.LoginProvider account.</p>
    <p class="text-info">
        You've successfully authenticated with <strong>@Model.LoginProvider</strong>.
        Please enter an email address for this site below and click the Register button to finish
        logging in.
    </p>
    <form asp-page-handler="Confirmation" asp-route-returnUrl="@Model.ReturnUrl" method="post">
        <div class="form-group has-feedback">
            <input asp-for="Input.Email" type="email" class="form-control" readonly placeholder="Email">
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            <span asp-validation-for="Input.Email" class="help-block"></span>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </div>

        <div class="row">
            <div class="col-xs-8">
                
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
            </div>
            <!-- /.col -->
        </div>
    </form>
</div>
<!-- /.login-box-body -->

src/Pages/Account/ForgotPassword.cshtml
@page
@model ForgotPasswordModel
@{
    ViewData["Title"] = "Forgot your password?";
}

<div class="login-box-body">
    <p class="login-box-msg">Enter your email</p>
    <form method="post">
        <div class="form-group has-feedback">
            <input asp-for="Input.Email" type="email" class="form-control" placeholder="Email">
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            <span asp-validation-for="Input.Email" class="help-block"></span>
        </div>
        <div class="row">
            <div class="col-xs-8">
                        
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Reset</button>
            </div>
            <!-- /.col -->
        </div>
    </form>
    <a asp-page="./Login">I already have a membership</a><br>
    <a asp-page="./Register" class="text-center">Register a new membership</a>
</div>
<!-- /.login-box-body -->
   

src/Pages/Account/ForgotPasswordConfirmation.cshtml
@page
@model ForgotPasswordConfirmationModel
@{
    ViewData["Title"] = "Reset confirmation";
}

<div class="login-box-body">
    <p class="login-box-msg">Please check your email to reset your password.</p>
</div>
<!-- /.login-box-body -->
    

src/Pages/Account/Login.cshtml
@page
@model LoginModel

@inject Microsoft.Extensions.Configuration.IConfiguration Configuration

@{
    ViewData["Title"] = "Log in";
}

<div class="login-box-body">
    <p class="login-box-msg">Ingrese sus datos</p>
    <form method="post">
        <div class="form-group has-feedback">
            <input asp-for="Input.Email" type="email" class="form-control" placeholder="email">
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            <span asp-validation-for="Input.Email" class="help-block"></span>
        </div>
        <div class="form-group has-feedback">
            <input asp-for="Input.Password" type="password" class="form-control" placeholder="contraseña">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            <span asp-validation-for="Input.Password" class="help-block"></span>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </div>
        <div class="row">
            <div class="col-xs-8">
                <div class="checkbox icheck">
                    <label>
                        <input asp-for="Input.RememberMe" type="checkbox"> Recordarme
                    </label>
                </div>
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Iniciar</button>
            </div>
            <!-- /.col -->
        </div>
        @Html.AntiForgeryToken()
    </form>
    <form asp-page="./ExternalLogin" asp-route-returnUrl="@Model.ReturnUrl" method="post" class="form-horizontal">
        <div class="social-auth-links text-center">
          
            @if (Configuration["Authentication:Facebook:IsEnabled"] == "true")
            {
            <button type="submit" class="btn btn-block btn-social btn-facebook btn-flat" name="provider" value="Facebook" title="Log in using your Facebook account">
                <i class="fa fa-facebook"></i> Sign in using Facebook
            </button>
            }

            @if (Configuration["Authentication:Google:IsEnabled"] == "true")
            {
            <button type="submit" class="btn btn-block btn-social btn-google btn-flat" name="provider" value="Google" title="Log in using your Google account">
                <i class="fa fa-google-plus"></i> Sign in using Google+
            </button>
            }
        </div>
    </form>
    <!-- /.social-auth-links -->
    <a asp-page="./ForgotPassword">Olvidé mi contraseña</a><br>
    <a asp-page="./Register" asp-route-returnUrl="@Model.ReturnUrl" class="text-center">Registrarse</a>
</div>
<!-- /.login-box-body -->

src/Pages/Account/LoginWith2fa.cshtml
@page
@model LoginWith2faModel
@{
    ViewData["Title"] = "Two-factor authentication";
}

<div class="login-box-body">
    <p class="login-box-msg">Two-factor authentication</p>
    <form method="post" asp-route-returnUrl="@Model.ReturnUrl">
        <input asp-for="RememberMe" type="hidden" />
        <div class="form-group has-feedback">
            <input asp-for="Input.TwoFactorCode" class="form-control" placeholder="Code" autocomplete="off">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            <span asp-validation-for="Input.TwoFactorCode" class="help-block"></span>
        </div>
        <div class="row">
            <div class="col-xs-8">
                <div class="checkbox icheck">
                    <label>
                        <input asp-for="Input.RememberMachine" type="checkbox"> Remember this computer
                    </label>
                </div>
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Log In</button>
            </div>
            <!-- /.col -->
        </div>
    </form>

    <p>
        Don't have access to your authenticator device? You can
        <a asp-page="./LoginWithRecoveryCode" asp-route-returnUrl="@Model.ReturnUrl">log in with a recovery code</a>.
    </p>
</div>
<!-- /.login-box-body -->

src/Pages/Account/LoginWithRecoveryCode.cshtml
@page
@model LoginWithRecoveryCodeModel
@{
    ViewData["Title"] = "Recovery code verification";
}

<div class="login-box-body">
    <p class="login-box-msg">Recovery code verification</p>
    <p>
        You have requested to log in with a recovery code. This login will not be remembered until you provide
        an authenticator app code at log in or disable 2FA and log in again.
    </p>
    <form method="post" asp-route-returnUrl="@Model.ReturnUrl">
        <div class="form-group has-feedback">
            <input asp-for="Input.RecoveryCode" class="form-control" placeholder="Code" autocomplete="off">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            <span asp-validation-for="Input.RecoveryCode" class="help-block"></span>
        </div>
        <div class="row">
            <div class="col-xs-8">
                &nbsp;
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Log In</button>
            </div>
            <!-- /.col -->
        </div>
    </form>

    <p>
        <a asp-page="./Login" asp-route-returnUrl="@Model.ReturnUrl" class="text-center">I want login again with Username/Password</a>
    </p>
</div>
<!-- /.login-box-body -->

src/Pages/Account/Register.cshtml
@page
@model RegisterModel
@{
    ViewData["Title"] = "Register";
}
<div class="login-box-body">
    <p class="login-box-msg">Registre sus datos</p>
    <form method="post">
        <div class="form-group has-feedback">
            <input asp-for="Input.FullName" type="text" class="form-control" placeholder="Nombre completo">
            <span class="glyphicon glyphicon-user form-control-feedback"></span>
            <span asp-validation-for="Input.FullName" class="help-block"></span>
        </div>
        <div class="form-group has-feedback">
            <input asp-for="Input.Email" type="email" class="form-control" placeholder="Email">
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            <span asp-validation-for="Input.Email" class="help-block"></span>
        </div>
        <div class="form-group has-feedback">
            <input asp-for="Input.Password" type="password" class="form-control" placeholder="Contraseña">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            <span asp-validation-for="Input.Password" class="help-block"></span>
        </div>
        <div class="form-group has-feedback">
            <input asp-for="Input.ConfirmPassword" type="password" class="form-control" placeholder="Repita la contraseña">
            <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
            <span asp-validation-for="Input.ConfirmPassword" class="help-block"></span>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </div>
        <div class="form-group has-feedback">
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input asp-for="Input.IsAgree" type="checkbox" required data-msg="Debes aceptar los términos."> Acepto los <a href="#">términos</a>
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Registrarse</button>
                </div>
                <!-- /.col -->
            </div>
            <span asp-validation-for="Input.IsAgree" class="help-block"></span>
        </div>
    </form>

    <div class="social-auth-links text-center">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-social btn-facebook btn-flat">
            <i class="fa fa-facebook"></i> Sign up using Facebook
        </a>
        <a href="#" class="btn btn-block btn-social btn-google btn-flat">
            <i class="fa fa-google-plus"></i> Sign up using Google+
        </a>
    </div>
            

    <a asp-page="./Login" asp-route-returnUrl="@Model.ReturnUrl" class="text-center">Ya poseo una cuenta</a>
</div>
<!-- /.form-box -->

src/Pages/Account/ResetPassword.cshtml
@page
@model ResetPasswordModel
@{
    ViewData["Title"] = "Reset password";
}

<div class="login-box-body">
    <p class="login-box-msg">Reset your password.</p>
    <form method="post">
        <input asp-for="Input.Code" type="hidden" />
        <div class="form-group has-feedback">
            <input asp-for="Input.Email" type="email" class="form-control" placeholder="Email">
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            <span asp-validation-for="Input.Email" class="help-block"></span>
        </div>
        <div class="form-group has-feedback">
            <input asp-for="Input.Password" type="password" class="form-control" placeholder="Password">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            <span asp-validation-for="Input.Password" class="help-block"></span>
        </div>
        <div class="form-group has-feedback">
            <input asp-for="Input.ConfirmPassword" type="password" class="form-control" placeholder="Retype password">
            <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
            <span asp-validation-for="Input.ConfirmPassword" class="help-block"></span>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </div>
        <div class="form-group has-feedback">
            <div class="row">
                <div class="col-xs-8">
                            
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Reset</button>
                </div>
                <!-- /.col -->
            </div>

        </div>
    </form>

    <a asp-page="./Login" class="text-center">Sign in using current password.</a>
</div>
<!-- /.form-box -->
    

src/Pages/Account/ResetPasswordConfirmation.cshtml
@page
@model ResetPasswordConfirmationModel
@{
    ViewData["Title"] = "Reset password confirmation";
}

<div class="login-box-body">
    <p class="login-box-msg">
        Your password has been reset. <br />
        Please <a asp-page="./Login">click here to log in</a>.
    </p>
</div>
<!-- /.login-box-body -->